name: circuit
baseurl: /circuit
description: Circuit Breaker for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.3-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
