name: circuit
baseurl: /circuit
description: Circuit Breaker for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0+4-c3b5ef06-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
